added useState hook to update profile. need to figure out the error message
./src/app/profile/UserDescription.tsx

Error:   × You're importing a component that needs `useState`. This React hook only works in a client component. To fix, mark the file (or its parent) with the `"use client"` directive.
  │
  │  Learn more: https://nextjs.org/docs/app/building-your-application/rendering/client-components
  │
  │
   ╭─[C:\Users\qingy\OneDrive\Desktop\studynotesdatabase\main_app\src\app\profile\UserDescription.tsx:1:1]
 1 │ import React, { useState } from 'react';
   ·                 ────────
 2 │
 3 │ interface Note {
 3 │     id: number;

   ╰────